name: Auto Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Deploy on App Server
      run: |
        echo "🚀 Deployment started"

        cd /home/ubuntu/django-realworld-example-app

        git pull origin main

        source venv/bin/activate

        pip install -r requirements.txt

        python manage.py migrate

        echo "✅ Deployment completed"
